language: php
sudo: true

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  - mkdir temp
  - cd temp
  - git clone https://gist.github.com/9a8e74487573f25bd83b59aac328bf6d.git .
  - sudo sh install-couchdb-2.0.0-travis-ci.sh
  - sleep 10
  - curl -X PUT localhost:5984/doctrine_test_database
  - composer install

script:
  - php vendor/bin/phpunit
